//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uk.JohnCook.dotnet.StreamController.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uk.JohnCook.dotnet.StreamController.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Controller.
        /// </summary>
        public static string application_name {
            get {
                return ResourceManager.GetString("application_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBS-websocket.
        /// </summary>
        public static string application_name_obs_websocket {
            get {
                return ResourceManager.GetString("application_name_obs-websocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string button_connect {
            get {
                return ResourceManager.GetString("button_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+r.
        /// </summary>
        public static string button_connect_accelerator {
            get {
                return ResourceManager.GetString("button_connect_accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string button_disconnect {
            get {
                return ResourceManager.GetString("button_disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+d.
        /// </summary>
        public static string button_disconnect_accelerator {
            get {
                return ResourceManager.GetString("button_disconnect_accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string button_reconnect {
            get {
                return ResourceManager.GetString("button_reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string button_save {
            get {
                return ResourceManager.GetString("button_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+s.
        /// </summary>
        public static string button_save_accelerator {
            get {
                return ResourceManager.GetString("button_save_accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon_dark_golden_rod {
            get {
                object obj = ResourceManager.GetObject("icon_dark_golden_rod", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon_dark_green {
            get {
                object obj = ResourceManager.GetObject("icon_dark_green", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon_neutral {
            get {
                object obj = ResourceManager.GetObject("icon_neutral", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon_red {
            get {
                object obj = ResourceManager.GetObject("icon_red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon_secondary {
            get {
                object obj = ResourceManager.GetObject("icon_secondary", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Connection.
        /// </summary>
        public static string menu_connection {
            get {
                return ResourceManager.GetString("menu_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Auto-Reconnect.
        /// </summary>
        public static string menu_connection_auto_reconnect {
            get {
                return ResourceManager.GetString("menu_connection_auto-reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Disconnect.
        /// </summary>
        public static string menu_connection_disconnect {
            get {
                return ResourceManager.GetString("menu_connection_disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reconnect.
        /// </summary>
        public static string menu_connection_reconnect {
            get {
                return ResourceManager.GetString("menu_connection_reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string menu_edit {
            get {
                return ResourceManager.GetString("menu_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Preferences.
        /// </summary>
        public static string menu_edit_preferences {
            get {
                return ResourceManager.GetString("menu_edit_preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string menu_file {
            get {
                return ResourceManager.GetString("menu_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string menu_file_close {
            get {
                return ResourceManager.GetString("menu_file_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt+F4.
        /// </summary>
        public static string menu_file_close_accelerator {
            get {
                return ResourceManager.GetString("menu_file_close_accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string menu_file_exit {
            get {
                return ResourceManager.GetString("menu_file_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift+Alt+F4.
        /// </summary>
        public static string menu_file_exit_accelerator {
            get {
                return ResourceManager.GetString("menu_file_exit_accelerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window.
        /// </summary>
        public static string menu_window {
            get {
                return ResourceManager.GetString("menu_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio _Check.
        /// </summary>
        public static string menu_window_audio_check {
            get {
                return ResourceManager.GetString("menu_window_audio-check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Audio Interfaces.
        /// </summary>
        public static string menu_window_audio_interfaces {
            get {
                return ResourceManager.GetString("menu_window_audio-interfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OBS.
        /// </summary>
        public static string menu_window_obs {
            get {
                return ResourceManager.GetString("menu_window_obs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Password is enabled but the password box still contains placeholder text..
        /// </summary>
        public static string new_password_placeholder_error {
            get {
                return ResourceManager.GetString("new_password_placeholder_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next time you open Preferences the password box will contain placeholder text..
        /// </summary>
        public static string new_password_set_message {
            get {
                return ResourceManager.GetString("new_password_set_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string text_minutes {
            get {
                return ResourceManager.GetString("text_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string text_seconds {
            get {
                return ResourceManager.GetString("text_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password Error.
        /// </summary>
        public static string title_new_password_error {
            get {
                return ResourceManager.GetString("title_new_password_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to obs-websocket Password Configured.
        /// </summary>
        public static string title_new_password_saved {
            get {
                return ResourceManager.GetString("title_new_password_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default _Capture.
        /// </summary>
        public static string tray_contextmenu_default_capture {
            get {
                return ResourceManager.GetString("tray_contextmenu_default-capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current default capture device, {0}.
        /// </summary>
        public static string tray_contextmenu_default_capture_default_automation_name_format {
            get {
                return ResourceManager.GetString("tray_contextmenu_default-capture_default_automation-name_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default _Render.
        /// </summary>
        public static string tray_contextmenu_default_render {
            get {
                return ResourceManager.GetString("tray_contextmenu_default-render", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current default render device, {0}.
        /// </summary>
        public static string tray_contextmenu_default_render_default_automation_name_format {
            get {
                return ResourceManager.GetString("tray_contextmenu_default-render_default_automation-name_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string tray_contextmenu_exit {
            get {
                return ResourceManager.GetString("tray_contextmenu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_nsure Custom Audio.
        /// </summary>
        public static string tray_contextmenu_toggle_app_audio {
            get {
                return ResourceManager.GetString("tray_contextmenu_toggle-app-audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item..
        /// </summary>
        public static string validation_error_ComboBoxOneItemSelected {
            get {
                return ResourceManager.GetString("validation_error_ComboBoxOneItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid hostname or IP address..
        /// </summary>
        public static string validation_error_Hostname {
            get {
                return ResourceManager.GetString("validation_error_Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number greater than zero..
        /// </summary>
        public static string validation_error_NumberGreaterZero {
            get {
                return ResourceManager.GetString("validation_error_NumberGreaterZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid port number..
        /// </summary>
        public static string validation_error_PortNumber {
            get {
                return ResourceManager.GetString("validation_error_PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last save attempt failed as there were errors above..
        /// </summary>
        public static string validation_error_window_preferences_save {
            get {
                return ResourceManager.GetString("validation_error_window_preferences_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AudioCheck.
        /// </summary>
        public static string window_audio_check_title {
            get {
                return ResourceManager.GetString("window_audio-check_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Control.
        /// </summary>
        public static string window_audio_interfaces_title {
            get {
                return ResourceManager.GetString("window_audio-interfaces_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetworkTest.
        /// </summary>
        public static string window_network_test_title {
            get {
                return ResourceManager.GetString("window_network-test_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Auto Scroll.
        /// </summary>
        public static string window_obs_auto_scroll {
            get {
                return ResourceManager.GetString("window_obs_auto-scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Received Data.
        /// </summary>
        public static string window_obs_received_data {
            get {
                return ResourceManager.GetString("window_obs_received-data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebSocketTest.
        /// </summary>
        public static string window_obs_title {
            get {
                return ResourceManager.GetString("window_obs_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Auto-scroll.
        /// </summary>
        public static string window_preferences_auto_scroll {
            get {
                return ResourceManager.GetString("window_preferences_auto-scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically _Reconnect.
        /// </summary>
        public static string window_preferences_automatic_reconnect {
            get {
                return ResourceManager.GetString("window_preferences_automatic-reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum reconnect delay in minutes.
        /// </summary>
        public static string window_preferences_backoff_max_automation_name {
            get {
                return ResourceManager.GetString("window_preferences_backoff_max_automation-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Maximum delay in minutes between connection attempts:.
        /// </summary>
        public static string window_preferences_backoff_max_label {
            get {
                return ResourceManager.GetString("window_preferences_backoff_max_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First reconnect delay in seconds.
        /// </summary>
        public static string window_preferences_backoff_min_automation_name {
            get {
                return ResourceManager.GetString("window_preferences_backoff_min_automation-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delay in seconds between 1st and 2nd connection attempt:.
        /// </summary>
        public static string window_preferences_backoff_min_label {
            get {
                return ResourceManager.GetString("window_preferences_backoff_min_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Connect on Launch.
        /// </summary>
        public static string window_preferences_connect_on_launch {
            get {
                return ResourceManager.GetString("window_preferences_connect-on-launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponential Back-off.
        /// </summary>
        public static string window_preferences_groupbox_backoff {
            get {
                return ResourceManager.GetString("window_preferences_groupbox_backoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URI.
        /// </summary>
        public static string window_preferences_groupbox_server_uri_label {
            get {
                return ResourceManager.GetString("window_preferences_groupbox_server-uri_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hostname:.
        /// </summary>
        public static string window_preferences_hostname_label {
            get {
                return ResourceManager.GetString("window_preferences_hostname_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string window_preferences_password_automation_name {
            get {
                return ResourceManager.GetString("window_preferences_password_automation-name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Port:.
        /// </summary>
        public static string window_preferences_port_label {
            get {
                return ResourceManager.GetString("window_preferences_port_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Scheme:.
        /// </summary>
        public static string window_preferences_scheme_label {
            get {
                return ResourceManager.GetString("window_preferences_scheme_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string window_preferences_title {
            get {
                return ResourceManager.GetString("window_preferences_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Use Password:.
        /// </summary>
        public static string window_preferences_use_password_label {
            get {
                return ResourceManager.GetString("window_preferences_use-password_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemTrayIcon.
        /// </summary>
        public static string window_system_tray_icon_title {
            get {
                return ResourceManager.GetString("window_system-tray-icon_title", resourceCulture);
            }
        }
    }
}
